# Site settings
title: UW ChemE 485 Process Design II
email: ccurtis7 -- AT -- uw.edu
description: "Comprehensive design of a specific process or product, including economic feasibility studies, utilization of market survey and plant location studies, process equipment design and optimization, and overall plant integration and layout."
url: "http://uw-cheme485.github.io"
twitter_username: derchadmeister
github_username:  uw-cheme486


# Build settings
markdown: kramdown
